language: java
script: mvn -Dfile.encoding=UTF-8 -Dproject.build.sourceEncoding=UTF-8 test
after_success: mvn -Dfile.encoding=UTF-8 -Dproject.build.sourceEncoding=UTF-8 clean cobertura:cobertura coveralls:report
