language: java
env:
  global:
  - MISFIT_CLOUD_BUILDER_SERVER="52.6.42.144"
  - MISFIT_CLOUD_BUILDER_USER="misfit"
  - MISFIT_CLOUD_BUILDER_PASSWORD="User@123"

before_script:
- curl http://$MISFIT_CLOUD_BUILDER_SERVER/downloads/misfit-cloud-builder-client-linux-386.tar.gz | tar xzv

script:
- mvn -Dfile.encoding=UTF-8 -Dproject.build.sourceEncoding=UTF-8 test
- ./misfit-cloud-builder-client --travis

after_success:
- mvn -Dfile.encoding=UTF-8 -Dproject.build.sourceEncoding=UTF-8 clean cobertura:cobertura coveralls:report

# branches:
#   only:
#   - master
#   - develop

# notifications:
#   hipchat: C5Ta9DcFxSNftnD2ZMtfRJN2SbUtRLuGDQy6JXmI@1467331
